### PR TITLE
Fixed RST formatting of the BIO document

### PR DESCRIPTION
**Pull request by JanSimek**

### CODE REVIEW

**Comment by JanSimek** [comment]
I noticed there a divergence between the description of Elevation flag in this document and on the [falloutmods wiki](https://falloutmods.fandom.com/wiki/MAP_File_Format):

> If (flag & 0x1) == 0 then ?? unknown.

versus

>  If (flag & 0x1) != 0 then the map is a savegame map (.SAV).

**Comment by adamkewley** [comment]
Oh my god, thank you for formatting these @JanSimek ! 

I mostly copied them over from various wikis / notes I found, maybe some from the original Russian team that reverse-engineered the files initially. Their formatting is terrible (sorry) and I copied them in-tree just to shield myself from the internet going down

**Comment by adamkewley** [comment]
The divergence is probably because someone has since updated the wiki with more up-to-date information. 

The docs in this repo are out of date :( I initially planned on editing all the various fallout file formats into a single sphinx documentation tree that I'd just generate a static site from. This would give engine developers basic offline documentation of the formats.

As with almost everything in this repo, I probably bit off more than I could handle with some of my ideas. There are *a lot* of  file formats in Fallout and I'd estimate that >50 % of the challange of writing a Fallout engine (e.g. like Falltergeist, darkfo, vault13) is understanding these formats. My ambition was to simplify the documentation of the formats a little bit.

I personally relied on the fan wiki and falltergeist's source-code to implement the parsers in `master`. Even doing that took quite a bit of time, and my file support is nowhere near the level that Falltergeist has. This is why I returned to trying to patch Falltergeist. That didn't work out, and I don't think there's enough interest in writing a clean implementation, so this code is kind of sitting around :(

**Comment by adamkewley** [comment]
Either way, this PR is highly appreciated. Really. I just haven't really had time to work on Fallout stuff for months :(

**Pull request merged**
